version: '3.8'

name: backend-game-tower

services:
  backend-game-tower-db:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: backend-game-tower-db
   ports:
     - 1433:1433
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=!Ntern2024